[tool.ruff]
# Enable both linting and formatting
line-length = 88
target-version = "py310"

# Rules to enable (defaults to common Python best practices)
select = ["E", "F", "I"]

# Ignore specific rules (optional, add as you go)
ignore = ["E501"]  # ignore long line warnings since formatter handles it

[tool.ruff.format]
# Match Black’s formatting style
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
